"""Tenant + BusinessProfile.

The BusinessProfile is the single most important object in the system. It is
produced by the Configurator agent at onboarding and it parameterises
extraction prompts, which modules are active, field labels, and alert rules.
Nothing downstream should hardcode textile assumptions — read the profile.
"""

import uuid

from sqlalchemy import Boolean, Column, DateTime, ForeignKey, String
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from app.models.base import Base, TimestampMixin


class Tenant(Base, TimestampMixin):
    __tablename__ = "tenant"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    business_name = Column(String(200), nullable=False)
    owner_name = Column(String(120))
    owner_phone = Column(String(20), unique=True, nullable=False)
    owner_email = Column(String(200))  # where the close-of-business digest goes
    city = Column(String(80))
    locale = Column(String(10), default="en")  # en | hi | gu | mr

    onboarded_at = Column(DateTime, nullable=True)
    is_active = Column(Boolean, default=True)

    # SHA-256 of the tenant's bearer token. The plaintext is shown once, at
    # onboarding, and never stored — see app/services/auth.py.
    api_token_hash = Column(String(64), unique=True, index=True, nullable=True)

    # Billing — prepaid annual is the default for the launch cohort.
    plan = Column(String(32), default="annual_prepaid")
    paid_until = Column(DateTime, nullable=True)

    profile = relationship("BusinessProfile", back_populates="tenant", uselist=False)


class BusinessProfile(Base, TimestampMixin):
    """Generated by the Configurator. Versioned so we can diff what the agent
    decided and roll back a bad configuration without re-onboarding."""

    __tablename__ = "business_profile"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id = Column(UUID(as_uuid=True), ForeignKey("tenant.id", ondelete="CASCADE"))
    version = Column(String(16), default="1")

    # ["wholesaler", "retail"] — multi-select at onboarding.
    segments = Column(JSONB, default=list, nullable=False)

    # Which modules are switched on for this tenant.
    # e.g. {"lots": true, "job_work": false, "dispatch": true, "catalog": false}
    modules = Column(JSONB, default=dict, nullable=False)

    # How this business actually talks: units, code formats, party aliases.
    # e.g. {"quantity_units": ["meter", "thaan"], "quality_code_regex": "^[A-Z]{2}-\\d{4}$",
    #       "rate_basis": "per_meter", "currency": "INR"}
    vocabulary = Column(JSONB, default=dict, nullable=False)

    # Alert thresholds the digest and ledger analyst use.
    # e.g. {"overdue_days": 45, "low_stock_meters": 200, "rate_deviation_pct": 20}
    rules = Column(JSONB, default=dict, nullable=False)

    # Few-shot examples harvested from this tenant's own corrections.
    examples = Column(JSONB, default=list, nullable=False)

    tenant = relationship("Tenant", back_populates="profile")

    def module_on(self, name: str) -> bool:
        return bool(self.modules.get(name, False))
